# ---- UPDATE-DESCRIPTOR-BEGIN ----
# targetNodes:
#   - id: 8c824c84e03de12e73fe286222c00faa3d8fd152
#   - id: 1c824c84e03de12e73fe286222c00faa3d8fd152
#   - id: 481029997EFfD67A74b48C98D763e2a2147e68A6
#   - id: "*"
# # use id: "*" to target all nodes
# # used 1440 to spread over a day.
# updateResolution: 120
# # can be immediate or scheduled
# updateMode: immediate
# updateInAction: true
# # can be commit id or latest
# commit: latest
# ---- UPDATE-DESCRIPTOR-END ----

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "200m"
    max-file: "3"

services:
  nginx:
    logging: *default-logging
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - .:/opt/orbs
    depends_on:
      - logger
    healthcheck:
      test: service nginx status || exit 1

  ethereum-reader:
    logging: *default-logging
    container_name: ethereum-reader
    image: lukerogerson1/management-service:v2.7.1-immediate
    command: "npm start"
    volumes:
      - ./.data/ethereum-reader:/opt/orbs/status
    environment:
      - DOCKER_COMPOSE_DESCRIPTOR_URL
      - INJECT_FAKE_GUARDIAN={"name":"jordalishNode","ip":"0x7F000001"}
      - NODE_ADDRESS
      - ETHEREUM_ENDPOINT
    healthcheck:
      test: node healthcheck.js || exit 1
    networks:
      default:
        aliases:
          - management-service

  matic-reader:
    logging: *default-logging
    container_name: matic-reader
    image: orbsnetworkstaging/management-service:v2.7.1-immediate
    command: "npm start"
    volumes:
      - ./.data/matic-reader:/opt/orbs/status
    environment:
      - INJECT_FAKE_GUARDIAN={"name":"jordalishNode","ip":"0x7F000001"}
      - NODE_ADDRESS
      - ETHEREUM_GENESIS_CONTRACT=0x35eA0D75b2a3aB06393749B4651DfAD1Ffd49A77
      - ETHEREUM_ENDPOINT=${MATIC_ENDPOINT}
      - ETHEREUM_FIRST_BLOCK=21700000
      - ETHEREUM_POLL_INTERVAL_SECONDS=300
    healthcheck:
      test: node healthcheck.js || exit 1

  ethereum-writer:
    logging: *default-logging
    container_name: ethereum-writer
    image: lukerogerson1/ethereum-writer:v1.7.3-main
    command: "npm start"
    volumes:
      - ./.data/ethereum-writer:/opt/orbs/status
    environment:
      - ETHEREUM_ELECTIONS_CONTRACT=0x02Ca9F2c5dD0635516241efD480091870277865b
      - ETHEREUM_ENDPOINT
      - NODE_PRIVATE_KEY
      - SIGNER_ENDPOINT
      - NODE_ADDRESS
      - MANAGEMENT_SERVICE_ENDPOINT=http://nginx/service/ethereum-reader
    healthcheck:
      test: node healthcheck.js || exit 1

  signer:
    logging: *default-logging
    container_name: signer
    image: orbsnetworkstaging/signer:v2.6.0-59e1b92f
    command: "/opt/orbs/orbs-signer"
    volumes:
      - ./.data/signer:/opt/orbs/status
    environment:
      - NODE_PRIVATE_KEY
      - NODE_ADDRESS
      - HTTP_ADDRESS=:80
    healthcheck:
      test: "/opt/orbs/healthcheck --url http://localhost:80 --output /opt/orbs/status/status.json"

  logger:
    logging: *default-logging
    container_name: logger
    build:
      context: ./logging
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
      - ./.data/logger:/opt/orbs/status
    environment:
      - STATUS_FILE_PATH=/opt/orbs/status/status.json
    healthcheck:
      test: ping -c 1 logger || exit 1

  vm-notifications:
    logging: *default-logging
    container_name: vm-notifications
    platform: linux/amd64
    image: orbsnetwork/vm-notifications:v1.0.31
    entrypoint: ["/opt/orbs/service"]
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
      - ./.data/vm-notifications:/opt/orbs/status
    environment:
      - MULTILOG_DISABLED=1
      - STATUS_FILE_PATH=/opt/orbs/status/status.json
    healthcheck:
      test: ping -c 1 logger || exit 1

  vm-lambda:
    logging: *default-logging
    container_name: vm-lambda
    image: orbsnetworkstaging/vm-lambda:v5
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
      - ./.data/vm-lambda:/opt/orbs/status
    environment:
      - NODE_ENV=prod
      - MULTILOG_DISABLED=1      
      - LAMBDA_GIT_TAG=feature/v5                                                                                                                                                                                              
      - LAMBDA_PROJECTS_DIR=./orbs-lambda/projects                                                                                                                                                                        
      - LAMBDA_MGMT_SERVICE_URL=http://nginx/service/ethereum-reader/status
      - LAMBDA_SIGNER_ENDPOINT=http://nginx/service/signer
      - LAMBDA_STATUS_JSON_PATH=./status/status.json 
    healthcheck:
      test: ping -c 1 logger || exit 1

  vm-twap:
    logging: *default-logging
    container_name: vm-twap
    platform: linux/amd64
    image: orbsnetwork/vm-twap:v1.19.31
    entrypoint: ["/opt/orbs/service"]
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
      - ./.data/vm-twap:/opt/orbs/status
    environment:
      - MULTILOG_DISABLED=1
      - STATUS_FILE_PATH=/opt/orbs/status/status.json
    depends_on:
      - ethereum-reader
    healthcheck:
      test: ping -c 1 logger || exit 1

  vm-verifier:
    logging: *default-logging
    container_name: vm-verifier
    image: orbsnetworkstaging/vm-verifier:v1.0.5
    restart: unless-stopped
    volumes:
      - ./.data/vm-verifier:/opt/orbs/status
    environment:
      - STATUS_FILE_PATH=/opt/orbs/status/status.json
    healthcheck:
      test: ping -c 1 logger || exit 1
  vm-l3-dummy-service:
    logging: *default-logging
    container_name: vm-l3-dummy-service
    image: orbsnetworkstaging/vm-l3-dummy-service:1.0.0
    restart: unless-stopped
    volumes:
      - ./.data/vm-l3-dummy-service:/opt/orbs/status
    environment:
      - MULTILOG_DISABLED=1
      - STATUS_FILE_PATH=/opt/orbs/status/status.json
    healthcheck:
      test: ping -c 1 logger || exit 1

networks:
  default:
    name: custom_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
