version: "3.7"

services:
  ingress:
    image: nginx
    volumes:
      # . current directory is /opt/orbs
      - /opt/orbs:/opt/orbs
      - ./swarm/nginx:/etc/nginx
      - /var/log/:/var/log
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
