version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - $HOME/deployment/nginx.conf:/etc/nginx/conf.d/default.conf # How can this be done more generically?
      - /opt/orbs/management-service:/opt/orbs/management-service
    depends_on:
      - management-service

  management-service:
    image: orbsnetworkstaging/management-service:v2.5.1-m1
    # Uncomment to use local image with M1 Mac
    # image: lukerogerson1/management-service:v0.0.1-m1
    command: "npm start -- --config /opt/orbs/config.json"
    volumes:
      # TEMP: should take values from node.env
      - $HOME/setup/config.json:/opt/orbs/config.json
      - /opt/orbs/management-service:/opt/orbs/status
    # env_file:
    #   - node.env

