version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    
    volumes:
      - $HOME/deployment/nginx.conf:/etc/nginx/conf.d/default.conf # How can this be done more generically?
      - /opt/orbs/management-service:/opt/orbs/management-service
    depends_on:
      - management-service

  management-service:
    container_name: management-service
    image: lukerogerson1/management-service:v2.7.1-immediate
    command: "npm start"
    volumes:
      - /opt/orbs/management-service:/opt/orbs/status
    env_file:      
      - public.env
      - private.env
      
  ethereum-writer:
    container_name: ethereum-writer
    image: lukerogerson1/ethereum-writer:v1.7.2-main
    command: "npm start"
    volumes:
      - /opt/orbs/ethereum-writer:/opt/orbs/status
    env_file:
      - public.env
      - private.env
    
  signer:
    container_name: signer
    image: orbsnetworkstaging/signer:v2.6.0-immediate
    command: "/opt/orbs/orbs-signer"
    volumes:
      - /opt/orbs/signer:/opt/orbs/status
    env_file:
      - public.env
      - private.env

  logs:
      container_name: logs
      # TODO: move to Orbs Docker Hub repo
      image: lukerogerson1/v3-logging:0.0.1
      volumes:
        - $PODMAN_SOCKET_PATH:/var/run/docker.sock