version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - $HOME/deployment/nginx.conf:/etc/nginx/conf.d/default.conf # How can this be done more generically?
      - /opt/orbs/management-service:/opt/orbs/management-service
    depends_on:
      - management-service

  management-service:
    container_name: management-service
    # Uncomment to use amd64 image
    # image: orbsnetworkstaging/management-service:v2.5.1-a4db0333
    image: orbsnetworkstaging/management-service:v2.5.1-m1
    command: "npm start -- --config /opt/orbs/config.json"
    volumes:
      # TEMP: should take values from node.env
      - $HOME/setup/config.json:/opt/orbs/config.json
      - /opt/orbs/management-service:/opt/orbs/status
    env_file:
      - public.env
      - private.env

  logs:
      container_name: logs
      # TODO: move to Orbs Docker Hub repo
      image: orbsnetworkstaging/v3x-log:v3.0.0
      volumes:
        - $PODMAN_SOCKET_PATH:/var/run/docker.sock

