name: smoke-test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker-in-Docker
        run: |
          sudo service docker start
          sleep 5

      - name: Build Docker image
        run: docker build -t test-ubuntu .

      - name: Start container
        env:
          ETH_ENDPOINT: ${{ secrets.ETH_ENDPOINT }}
        run: |
          docker run -d -p 80:80 -e ETH_ENDPOINT=$ETH_ENDPOINT --privileged --name smoke_test test-ubuntu tail -f /dev/null

      - name: Run install script
        run: |
          docker exec smoke_test /bin/bash -c "source ./setup/install.sh --skip-req"

      - name: Check ethereum-reader's status is being served using legacy name (management-service)
        run: |
          curl -f http://localhost/service/management-service/status

      - name: Check ethereum-reader's status is being served using v4 name
        run: |
          curl -f http://localhost/service/ethereum-reader/status

      - name: Check manager's status is being served using legacy name (boyar)
        run: |
          curl -f http://localhost/service/boyar/status

      - name: Check manager's status is being served using v4 name
        run: |
          curl -f http://localhost/service/manager/status

      - name: Check logger's status is being served using legacy name (logs-service)
        run: |
          curl -f http://localhost/service/logs-service/status

      - name: Check logger's status is being served using v4 name
        run: |
          curl -f http://localhost/service/logger/status

      - name: Cleanup container
        if: always()
        run: |
          docker stop smoke_test
          docker rm smoke_test

      - name: Clean up Docker
        if: always()
        run: sudo service docker stop
